version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker-production/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: ./docker-production/rails/Dockerfile
    tty: true
    stdin_open: true
