version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
  app:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - .:/findpro-bangkok
      - public_data:/findpro-bangkok/public
      - tmp_data:/findpro-bangkok/tmp
      - log_data:/findpro-bangkok/log
    tty: true
    depends_on:
      - db
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - public_data:/findpro-bangkok/public
      - tmp_data:/findpro-bangkok/tmp
    depends_on:
      - app
